app = "tm-dfvu-db"
primary_region = "fra"

[build]
  image = "mysql:8.0"

[env]
  MYSQL_DATABASE = "testimonials"
  MYSQL_USER = "app"

[processes]
  app = "--datadir /data/mysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=128M"

[[mounts]]
  source = "mysqldata"
  destination = "/data"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
