<?php

declare(strict_types=1);

/**
 * Regenerates database/seed.sql from tests/fixtures/landings.json.
 * Usage: php database/build-seed.php > database/seed.sql
 * Deterministic: uses a fixed RNG seed so the output is stable across runs.
 *
 * Landing row shape: array{id:int,parent_sku:string,country:string,is_master:bool,url:string,title:string,description:?string,image:?string,status:?string}
 */

mt_srand(20260913);

/** @var array{data:list<array{id:int,parent_sku:string,country:string,is_master:bool,url:string,title:string,description:?string,image:?string,status:?string}>,meta:array{count:int,total:int,limit:int,offset:int,products:int,generated_at:string}} $fixture */
$fixture = json_decode((string) file_get_contents(__DIR__ . '/../tests/fixtures/landings.json'), true, 512, JSON_THROW_ON_ERROR);
$rows = $fixture['data'];

$q = static fn (?string $v): string => $v === null ? 'NULL' : "'" . str_replace(['\\', "'", "\n", "\r"], ['\\\\', "\\'", '\n', '\r'], $v) . "'";

$out = [];
$out[] = '-- Testimonials Manager — demo seed. Generated by database/build-seed.php; safe to re-run (idempotent).';
$out[] = 'SET NAMES utf8mb4;';
$out[] = 'SET FOREIGN_KEY_CHECKS = 0;';
$out[] = "INSERT INTO users (id, username, password_hash, display_name) VALUES (1, 'admin', " . $q(password_hash('admin123', PASSWORD_DEFAULT)) . ", 'Demo Admin')\n  ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), display_name = VALUES(display_name);";

// products from masters (fallback: first landing of the sku)
/** @var array<string,list<array{id:int,parent_sku:string,country:string,is_master:bool,url:string,title:string,description:?string,image:?string,status:?string}>> $bySku */
$bySku = [];
foreach ($rows as $r) {
    $bySku[$r['parent_sku']][] = $r;
}
$productId = 0;
/** @var array<string,int> $skuToId */
$skuToId = [];
$productValues = [];
foreach ($bySku as $sku => $list) {
    $master = null;
    foreach ($list as $r) {
        if ($r['is_master']) {
            $master = $r;
        }
    }
    $master ??= $list[0];
    $skuToId[$sku] = ++$productId;
    $productValues[] = sprintf('(%d, %s, %s, %s, %s)', $productId, $q($sku), $q($master['title']), $q($master['description']), $q($master['image']));
}
$out[] = "INSERT INTO products (id, parent_sku, title, description, image) VALUES\n  " . implode(",\n  ", $productValues) . "\n  ON DUPLICATE KEY UPDATE title = VALUES(title), description = VALUES(description), image = VALUES(image);";

$landingValues = [];
foreach ($rows as $r) {
    $landingValues[] = sprintf('(%d, %d, %s, %d, %s, %s, %s, %s, %s, \'2026-09-13 12:00:00\')', $r['id'], $skuToId[$r['parent_sku']], $q($r['country']), $r['is_master'] ? 1 : 0, $q($r['url']), $q($r['title']), $q($r['description']), $q($r['image']), $q($r['status']));
}
$out[] = "INSERT INTO landings (id, product_id, country, is_master, url, title, description, image, status, last_synced_at) VALUES\n  " . implode(",\n  ", $landingValues) . "\n  ON DUPLICATE KEY UPDATE product_id = VALUES(product_id), url = VALUES(url), title = VALUES(title), description = VALUES(description), image = VALUES(image), status = VALUES(status), removed_at = NULL;";

// testimonials: every master gets 3–6, every third localised landing gets 1–3.
/** @var array<string,list<array{0:string,1:string}>> $names */
$names = [
    'EN' => [['James Miller', 'male'], ['Emily Clark', 'female'], ['Alex Morgan', 'unisex']],
    'SI' => [['Janez Novak', 'male'], ['Maja Kovač', 'female']],
    'IT' => [['Mario Rossi', 'male'], ['Giulia Bianchi', 'female']],
    'DE' => [['Lukas Schmidt', 'male'], ['Anna Müller', 'female']],
    'BG' => [['Георги Иванов', 'male'], ['Мария Петрова', 'female']],
    'GR' => [['Γιώργος Παπαδόπουλος', 'male'], ['Ελένη Νικολάου', 'female']],
    'TR' => [['Mehmet Yılmaz', 'male'], ['Ayşe Kaya', 'female']],
    'CZ' => [['Jan Novák', 'male'], ['Eva Dvořáková', 'female']],
];
/** @var list<string> $texts */
$texts = [
    'Absolutely love it — arrived in two days and works exactly as described.',
    'Great value for money. My whole family uses it every day now.',
    'Solid build quality, easy setup. Would buy again.',
    'Not bad at all, though the manual could be clearer.',
    'Exceeded my expectations. Customer support was quick and friendly.',
];
$testimonialValues = [];
$imageValues = [];
$tid = 0;
$imgId = 0;
foreach ($rows as $i => $r) {
    $count = $r['is_master'] ? mt_rand(3, 6) : ($i % 3 === 0 ? mt_rand(1, 3) : 0);
    $pool = $names[$r['country']] ?? $names['EN'];
    for ($n = 0; $n < $count; $n++) {
        [$name, $gender] = $pool[$n % count($pool)];
        $rating = mt_rand(0, 3) === 0 ? 'NULL' : (string) mt_rand(3, 5);
        $active = mt_rand(0, 9) === 0 ? 0 : 1;
        $tid++;
        $testimonialValues[] = sprintf('(%d, %d, %s, %s, %s, %s, %s, %d, %d, 1, 1)', $tid, $r['id'], $q($name), $q($texts[($n + $i) % count($texts)]), $rating, $q($gender), $q($r['url']), $active, $n);
        if ($n === 0) {
            $imgId++;
            $uuid = sprintf('%08x-%04x-4%03x-8%03x-%012x', mt_rand(0, 0xffffffff), mt_rand(0, 0xffff), mt_rand(0, 0xfff), mt_rand(0, 0xfff), mt_rand(0, 0xffffffff));
            $imageValues[] = sprintf("(%d, %d, '%s.jpg', '%s_thumb.jpg', 'image/jpeg', 24576, 640, 480, 0, 1)", $imgId, $tid, $uuid, $uuid);
        }
    }
}
$out[] = "INSERT INTO testimonials (id, landing_id, author_name, text, rating, gender, url, is_active, sort_order, created_by, updated_by) VALUES\n  " . implode(",\n  ", $testimonialValues) . "\n  ON DUPLICATE KEY UPDATE author_name = VALUES(author_name), text = VALUES(text), rating = VALUES(rating), gender = VALUES(gender), url = VALUES(url), is_active = VALUES(is_active), sort_order = VALUES(sort_order);";
$out[] = "INSERT INTO testimonial_images (id, testimonial_id, filename, thumb_filename, mime, size_bytes, width, height, sort_order, created_by) VALUES\n  " . implode(",\n  ", $imageValues) . "\n  ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);";
$out[] = 'SET FOREIGN_KEY_CHECKS = 1;';

echo implode("\n\n", $out), "\n";
